import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { loadYamlFile } from "../yaml-utils.js";
import { isSchemaField } from "../schema.js";
import type { SchemaField } from "../schema.js";

function inferTypeName(type?: string): string {
	switch (type) {
		case "string": return "string";
		case "number": return "number";
		case "boolean": return "boolean";
		case "array": return "unknown[]";
		default: return "unknown";
	}
}

function generateInterface(def: Record<string, unknown>, indent = "\t"): string {
	const lines: string[] = [];
	for (const [key, value] of Object.entries(def)) {
		if (isSchemaField(value)) {
			const field = value as SchemaField;
			const typeName = inferTypeName(field.type);
			const optional = Boolean(field.optional || field.default !== undefined);
			lines.push(`${indent}${key}${optional ? "?" : ""}: ${typeName};`);
		} else if (typeof value === "object" && value !== null) {
			lines.push(`${indent}${key}: {`);
			lines.push(generateInterface(value as Record<string, unknown>, `${indent}\t`));
			lines.push(`${indent}};`);
		}
	}
	return lines.join("\n");
}

export interface TypegenOptions {
	schemaPath: string;
	output?: string | undefined;
}

export function runTypegen(options: TypegenOptions): void {
	const raw = loadYamlFile(options.schemaPath);

	const outputPath = options.output ?? resolve(process.cwd(), "config.types.ts");

	const iface = generateInterface(raw);

	const content = `// Auto-generated by @jd/config. Do not edit.\n\nexport interface AppConfig {\n${iface}\n}\n`;
	writeFileSync(outputPath, content, "utf-8");
	console.log(`  OK    ${outputPath}`);
}
